# Generated by Django 5.2.10 on 2026-01-10 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Nome")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                ("phone", models.CharField(max_length=30, verbose_name="Telefone")),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="WhatsApp"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="agents/", verbose_name="Foto"
                    ),
                ),
            ],
            options={
                "verbose_name": "Agente",
                "verbose_name_plural": "Agentes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Nome")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=30, verbose_name="Telefone")),
                (
                    "property_type",
                    models.CharField(max_length=50, verbose_name="Tipo de Propriedade"),
                ),
                (
                    "location",
                    models.CharField(max_length=200, verbose_name="Localização"),
                ),
                ("details", models.TextField(blank=True, verbose_name="Detalhes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Solicitação de Avaliação",
                "verbose_name_plural": "Solicitações de Avaliação",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descrição")),
                (
                    "location",
                    models.CharField(max_length=200, verbose_name="Localização"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Preço (MZN)"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("apartamento", "Apartamento"),
                            ("casa", "Casa"),
                            ("terreno", "Terreno"),
                            ("comercial", "Comercial"),
                            ("condominio", "Condomínio"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("venda", "Venda"), ("arrendamento", "Arrendamento")],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "bedrooms",
                    models.PositiveIntegerField(default=0, verbose_name="Quartos"),
                ),
                (
                    "bathrooms",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Casas de Banho"
                    ),
                ),
                (
                    "area",
                    models.PositiveIntegerField(
                        default=0, help_text="m²", verbose_name="Área"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Destaque"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Verificado"),
                ),
                (
                    "amenities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de comodidades como ['garagem', 'piscina', 'jardim']",
                        verbose_name="Comodidades",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="properties",
                        to="core.agent",
                        verbose_name="Agente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Propriedade",
                "verbose_name_plural": "Propriedades",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Nome")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                ("phone", models.CharField(max_length=30, verbose_name="Telefone")),
                ("message", models.TextField(verbose_name="Mensagem")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.property",
                        verbose_name="Propriedade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem de Contacto",
                "verbose_name_plural": "Mensagens de Contacto",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="properties/", verbose_name="Imagem"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.property",
                        verbose_name="Propriedade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem da Propriedade",
                "verbose_name_plural": "Imagens das Propriedades",
                "ordering": ["order", "id"],
            },
        ),
    ]
