# Generated by Django 4.2.7 on 2026-01-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="accepts_financing",
            field=models.BooleanField(
                default=False, verbose_name="Aceita Financiamento"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="accepts_pets",
            field=models.BooleanField(default=False, verbose_name="Aceita Animais"),
        ),
        migrations.AddField(
            model_name="property",
            name="address",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Endereço"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="availability_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Disponibilidade"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Cidade"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="condominium_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Condomínio (MZN/mês)",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="energy_class",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Classe Energética"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="floor_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Andar"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="furnished",
            field=models.BooleanField(default=False, verbose_name="Mobilado"),
        ),
        migrations.AddField(
            model_name="property",
            name="heating_type",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Sistema de Aquecimento",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="internal_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observações Internas"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="iptu",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="IPTU/Imposto Anual (MZN)",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                max_digits=10,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                max_digits=10,
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="monthly_expenses",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Despesas Mensais (MZN)",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="neighborhood",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Bairro"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="orientation",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Orientação Solar"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="parking_spaces",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Vagas de Estacionamento"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="property_condition",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Estado de Conservação",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="reference_code",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Código de Referência",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="suites",
            field=models.PositiveIntegerField(default=0, verbose_name="Suites"),
        ),
        migrations.AddField(
            model_name="property",
            name="toilets",
            field=models.PositiveIntegerField(default=0, verbose_name="WC/Lavabos"),
        ),
        migrations.AddField(
            model_name="property",
            name="total_floors",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Total de Andares"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="useful_area",
            field=models.PositiveIntegerField(
                blank=True, help_text="m²", null=True, verbose_name="Área Útil"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="year_built",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Ano de Construção"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="zip_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Código Postal"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="area",
            field=models.PositiveIntegerField(
                default=0, help_text="m²", verbose_name="Área Total"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="bathrooms",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Casas de Banho Completas"
            ),
        ),
    ]
