# Generated by Django 4.2.7 on 2026-01-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_property_accepts_financing_property_accepts_pets_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="country",
            field=models.CharField(
                default="Moçambique", max_length=100, verbose_name="País"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="currency",
            field=models.CharField(
                choices=[
                    ("MZN", "Metical Moçambicano"),
                    ("USD", "Dólar Americano"),
                    ("EUR", "Euro"),
                    ("ZAR", "Rand Sul-Africano"),
                ],
                default="MZN",
                max_length=3,
                verbose_name="Moeda",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="district",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Distrito"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="ipra",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="IPRA (Imposto Predial Anual)",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="land_area",
            field=models.PositiveIntegerField(
                blank=True, help_text="m²", null=True, verbose_name="Área do Terreno"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="legal_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("duat", "DUAT (Direito de Uso e Aproveitamento da Terra)"),
                    ("direito_uso", "Direito de Uso"),
                    ("escritura", "Escritura Pública"),
                    ("regularizacao", "Em Regularização"),
                    ("concessao", "Concessão"),
                ],
                max_length=20,
                null=True,
                verbose_name="Situação Legal",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="province",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Província"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="condominium_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Condomínio (por mês)",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="iptu",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="IPTU/Imposto Anual (DEPRECADO)",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="monthly_expenses",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Despesas Mensais",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=14, verbose_name="Preço"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="type",
            field=models.CharField(
                choices=[
                    ("apartamento", "Apartamento"),
                    ("apartamento_em_condominio", "Apartamento em Condomínio"),
                    ("casa", "Casa"),
                    ("terreno", "Terreno"),
                    ("comercial", "Comercial"),
                    ("empreendimento", "Empreendimento"),
                ],
                max_length=30,
                verbose_name="Tipo",
            ),
        ),
    ]
