# Generated by Django 4.2.7 on 2026-01-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_property_country_property_currency_property_district_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="propertyimage",
            options={
                "ordering": ["-is_primary", "order", "id"],
                "verbose_name": "Imagem da Propriedade",
                "verbose_name_plural": "Imagens das Propriedades",
            },
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="Imagem Principal"),
        ),
    ]
