# Generated by Django 4.2.7 on 2026-01-12 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_propertyimage_options_propertyimage_is_primary"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        upload_to="properties/documents/", verbose_name="Documento"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nome do Documento"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tipo de Documento"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Enviado em"),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.property",
                        verbose_name="Propriedade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento da Propriedade",
                "verbose_name_plural": "Documentos das Propriedades",
                "ordering": ["uploaded_at"],
            },
        ),
    ]
