# Generated by Django 4.2.7 on 2026-01-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_propertydocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Número de Visualizações"
            ),
        ),
    ]
