# Generated by Django 4.2.7 on 2026-02-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_pushsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="pushsubscription",
            name="bedrooms_min",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Quartos Mínimos"
            ),
        ),
        migrations.AddField(
            model_name="pushsubscription",
            name="location_filters",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Filtros de Localização"
            ),
        ),
        migrations.AddField(
            model_name="pushsubscription",
            name="notify_new_properties",
            field=models.BooleanField(default=True, verbose_name="Novas Propriedades"),
        ),
        migrations.AddField(
            model_name="pushsubscription",
            name="notify_price_changes",
            field=models.BooleanField(default=True, verbose_name="Mudanças de Preço"),
        ),
        migrations.AddField(
            model_name="pushsubscription",
            name="notify_recommendations",
            field=models.BooleanField(default=False, verbose_name="Recomendações"),
        ),
        migrations.AddField(
            model_name="pushsubscription",
            name="notify_status_changes",
            field=models.BooleanField(default=True, verbose_name="Mudanças de Status"),
        ),
        migrations.AddField(
            model_name="pushsubscription",
            name="price_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="Preço Máximo",
            ),
        ),
        migrations.AddField(
            model_name="pushsubscription",
            name="price_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="Preço Mínimo",
            ),
        ),
        migrations.AddField(
            model_name="pushsubscription",
            name="property_types",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Tipos de Propriedade"
            ),
        ),
        migrations.AddField(
            model_name="pushsubscription",
            name="quiet_hours_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Horário Silencioso Ativo"
            ),
        ),
        migrations.AddField(
            model_name="pushsubscription",
            name="quiet_hours_end",
            field=models.TimeField(
                default="08:00", verbose_name="Fim Horário Silencioso"
            ),
        ),
        migrations.AddField(
            model_name="pushsubscription",
            name="quiet_hours_start",
            field=models.TimeField(
                default="22:00", verbose_name="Início Horário Silencioso"
            ),
        ),
    ]
