# Generated by Django 4.2.7 on 2026-02-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_pushsubscription_bedrooms_min_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryWatermarkedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_image",
                    models.ImageField(
                        upload_to="temp_watermark/", verbose_name="Imagem Original"
                    ),
                ),
                (
                    "watermarked_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="temp_watermark/",
                        verbose_name="Imagem com Marca D'água",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="Nome Original"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Imagem Temporária com Marca D'água",
                "verbose_name_plural": "Imagens Temporárias com Marca D'água",
                "ordering": ["-created_at"],
            },
        ),
    ]
